language: node_js
node_js:
- 9.10.1

before_script:
- npm install --only=prod

script:
- "./node_modules/.bin/ng build --prod --aot"

deploy:
  provider: firebase
  skip-cleanup: true
  token:
    secure: k7/beDs+b6jH2hUQ7HtbpNiqT7scmBNy28tcj7DQA2fB66x9Q/jugVAUv1hcU+hZBqy7Bw008OfracvpJXV46U2gSOHHxCBQg1le7gqb/+Kcb0qwjkNrag0HwlunutHvtKTtUrE2c3uueksT/VM0p73bjJTTMA1wc3eUfZhY1fC44Dm0rFcpsn9oSL0vN4wyfm3RSxN1c1JX2+7vZxRM247Nd3xoXAdRQDLpgqq/QE1fnpD8x7QW5o/UBxVgZj43T7G8YoV8nAHTjEWerIzy7d1QL4WYT8TvmvcpXK719YaKzZBqmNP2J6/lf704vz2JVOo188kFbdUZYI4flXJoRc7M7e8SMbxhcnzUk24cpqemUEX1OdvQSDhWzCwbafg4EDujE6FQ/d6Z6+wuLanMfXH4LOHSuaITNpctXvajwbVc/KhK0S4MIrU8Amn+PXvg/AN/RB2pgCd8BDrtkPfK0/LhQtRMg3yndGtfEyQIBYSEZgsLuSW+SGj50QefiyOKPfrjetpYeqB40dvBrTbNULwqbdCIxBBRTW6ZfyIe8uEnFN8diDTIwHBhktVmIS262gwxxdOGBbHLnTuY8RszvhR6IQ34IWWjayPxJyHZJPo+44BeBOntpKLhmk0mGetSPBhY+9p6CR9WLi6jMHLLDzuODunVv0TTiJv2yfAkHvE=
  project: okty-7e60c
  on:
    repo: Okty-io/okty
    branch: master
